Fix: Completed lic7 through usage of magnitude as distance Issue #18
tjex/decide-g26 pull request #38
Opened 2023-01-27 14:47 UTC by Darpos

2023-01-28 11:09 UTC, a-kbd commented on src/main/CMV.java
> +            double magnitudeIJ = Math.sqrt(Math.pow(vectorIJ[0],2) + Math.pow(vectorIJ[1],2));
there is a euclidean_distance function you could've used

2023-01-28 11:14 UTC, a-kbd requested changes
see comments, also I believe I read Anders said LICs shouls stil lreturn boolean

2023-01-28 11:14 UTC, a-kbd commented on src/main/CMV.java
> +            int j = i + K_PTS;
I believe it should be j=i+K_PTS+1 cause they should be separated by that many intervening points. If i=0, j will be at index K_PTS and there would only be K_PTS - 1 points in between

2023-01-28 11:14 UTC, a-kbd commented on src/main/CMV.java
> +            double magnitudeIJ = Math.sqrt(Math.pow(vectorIJ[0],2) + Math.pow(vectorIJ[1],2));
there is a euclidean_distance function you could've used, not super important though

2023-01-29 13:34 UTC, a-kbd requested changes

2023-01-29 13:34 UTC, a-kbd commented on src/junit/LIC_test.java
> +    public void checkIfValidGivesTrueLic7(){
This test fails for me

2023-01-29 14:53 UTC, Darpos commented
Chill with this one, has some bugs

2023-01-29 14:58 UTC, Darpos commented
Ready for acceptance.

2023-01-29 18:25 UTC, a-kbd approved these changes
You could've used the euclidean_distance helper function directly instead of vector_subtraction→vector_magnitude but it still works and all tests pass so looks good to me :+1:

2023-01-29 18:25 UTC, merged