Feature: Implemented lic12 /issue #10
tjex/decide-g26 pull request #46
Opened 2023-01-27 16:28 UTC by Darpos

Get compile errors with accessing fields through parameters, but worked previously and it's been used elsewhere in code so it should be fine.

2023-01-28 09:52 UTC, andersblomqvist requested changes
We decided upon using `-1 = NOTUSED`, `0 = ORR` and `1 = ANDD`. All the LICs should still return a boolean value.

Additionally, every new feature should also contain a test. Change the return type to a boolean and add a test and this will be fine.

2023-01-28 14:47 UTC, andersblomqvist requested changes

2023-01-28 14:47 UTC, andersblomqvist commented on src/junit/LIC_test.java
> +    /*
From the assessment criteria on [Canvas](https://canvas.kth.se/courses/37918/assignments/235345): 

* The contract that is tested is clearly formulated in natural language
* The assertions of the tests correctly and completely assess the contract

I think the natural language part is missing, which should define what the test is testing and expectation.

2023-01-28 18:05 UTC, Darpos commented
Issues with the file don't accept

2023-01-28 18:35 UTC, Darpos commented
> Issues with the file don't accept

My test don't run on this branch, trying to fix so don't accept

2023-01-29 10:37 UTC, andersblomqvist requested changes

2023-01-29 10:37 UTC, andersblomqvist commented on src/junit/LIC_test.java
> +        assertTrue(cmv.lic5_calculate());
This causes an error due to function is private. There must been a mistake by removing the functioning code `cmv.get_cmv_value(5)`.

2023-01-29 10:37 UTC, andersblomqvist commented on src/junit/LIC_test.java
> +        assertFalse(cmv.lic5_calculate());
Here as well.

2023-01-29 14:37 UTC, andersblomqvist approved these changes
👍

2023-01-29 14:38 UTC, merged