doc : initial readme.md draft : issue/51
tjex/decide-g26 pull request #60
Opened 2023-01-28 15:57 UTC by tjex

Hey gang. 
This addresses issue #51 (documentation and statement of contributions)

Here's the first draft of the readme. 
Could someone double check I've summarised the functions correctly? 

And additionally, could each of you **comment below** with your statement of contributions (ie the primary work that you've done / that you're working on). 

I'll then add the additions / edits and repush for another review. 

Thanks.

2023-01-28 16:28 UTC, tjex commented
Note that the P+ criteria of doing something 'remarkable and for which we are proud' is also part of the documentation. As linked above.
 
I think we're all on that page anyway? It's for sure been a successful collaboration in terms of coordinating 5 people in a repo only after one day of organisation and it being many (if not all) of our first experiences working with this many people in a branch/PR/merge environment?

2023-01-28 16:36 UTC, andersblomqvist requested changes
Looks good, you could enclose the Decide() function with inline code markings, [help](https://www.markdownguide.org/basic-syntax/#code). Then it will look like this: `Decide()`. Makes it easier to read.

My contributions:
* Project code setup
* JUnit Test skeleton
* Implemented FUV
* Implemented LIC6
* Fixed PUM and created its tests

2023-01-28 18:00 UTC, Darpos commented
My contributions:

Implemented LIC2 + tests
Implemented LIC4 + tests
Implemented LIC5 + tests
Implemented LIC7 + tests
Implemented LIC11 + tests
Implemented LIC12 + tests
Implemented LIC14 + tests
Helped out with the code skeleton for CMV.java

2023-01-28 18:34 UTC, a-kbd commented
My contributions:
LICs 0,3,9,10 + tests
helper functions for some of the LICs
Parameters class
CMV class skeleton

2023-01-28 18:36 UTC, a-kbd requested changes

2023-01-28 18:36 UTC, a-kbd commented on README.md
> +The dev team for Decide() is combrised of:
typo combrised→comprised

2023-01-29 13:24 UTC, coffecup25 commented
My contributions:
LIC:s 1,8 + tests
Helper function for calculating radius of circumscribed circle
Fixing bugs in testing functions
Contributed to Github branch protection rules
Helped with project structure

2023-01-29 17:34 UTC, tjex commented on README.md
> +The dev team for Decide() is combrised of:
done. thanks

2023-01-29 20:03 UTC, tjex commented
I think the readme is almost done. Just needs to be finalised once the final elements of the Paramaters.java and Main.java get finished. Then I can reference them too.

2023-01-30 17:29 UTC, merged